# Generated by Django 5.0.1 on 2024-05-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="messages",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, default="1941-12-07"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="messages",
            name="user_unique_key",
            field=models.CharField(blank=True, default="", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="messages",
            name="user2",
            field=models.CharField(default="", max_length=4000),
        ),
    ]
