# Generated by Django 5.0.1 on 2024-05-11 11:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_messages_timestamp_messages_user_unique_key_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="messages",
            name="timestamp",
        ),
    ]
