# Generated by Django 5.0.1 on 2024-05-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_remove_messages_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="messages",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, default="1941-12-07"),
            preserve_default=False,
        ),
    ]
